on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_REPOSITORY}}:${BRANCH_NAME}
    - name: Push docker image to dockerhub
      run: |
        echo ${{secrets.DOCKERHUB_TOKEN}} | docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
        docker push ${{secrets.DOCKERHUB_REPOSITORY}}:${BRANCH_NAME}
        rm -f ${HOME}/.docker/config.json


