on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Echoing brach name
      run: echo "${BRANCH_NAME}"